name: Fetch Stocks Data

on:
  schedule:
    - cron: '0 15 * * *' # Runs at 8:30 PM IST
  workflow_dispatch: # Allows manual trigger too

jobs:
  fetch-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ingest script
        run: curl -s -X GET 'https://stocker.co.in/api/ingestStocks'
